name: Deploy Backend to Raspberry Pi

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend to Raspberry Pi
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python Virtual Environment and Install Dependencies
        run: |
          APP_DIR="/opt/pi-remote-control"
          VENV_DIR="$APP_DIR/venv"
          
          # Create app directory if it doesn't exist
          sudo mkdir -p $APP_DIR
          sudo chown -R $USER:$USER $APP_DIR

          # Create venv if it doesn't exist
          if [ ! -d "$VENV_DIR" ]; then
            python3 -m venv $VENV_DIR
          fi

          # Install dependencies inside the venv
          $VENV_DIR/bin/pip install --upgrade pip
          $VENV_DIR/bin/pip install websockets adafruit-circuitpython-neopixel rpi_ws281x

      - name: Setup service
        run: |
          APP_DIR="/opt/pi-remote-control"
          VENV_DIR="$APP_DIR/venv"
          
          # Copy backend code
          sudo cp backend/server.py $APP_DIR/server.py
          sudo chmod +x $APP_DIR/server.py
          
          # Create or update systemd service file
          sudo tee /etc/systemd/system/pi-remote-led-server.service > /dev/null << EOT
          [Unit]
          Description=NeoPixel LED Controller WebSocket Server
          After=network.target
          
          [Service]
          ExecStart=$VENV_DIR/bin/python $APP_DIR/server.py
          WorkingDirectory=$APP_DIR
          StandardOutput=inherit
          StandardError=inherit
          Restart=always
          User=root
          
          [Install]
          WantedBy=multi-user.target
          EOT
          
          # Reload systemd, enable and restart service
          sudo systemctl daemon-reload
          sudo systemctl enable pi-remote-led-server.service
          sudo systemctl restart pi-remote-led-server.service
          
          # Check service status
          sudo systemctl status pi-remote-led-server.service